// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qoHY3_nWT1Emk1Kdi6QnvlM19xy56m4',
    appId: '1:577557834859:web:206f55f96412b7a190d52e',
    messagingSenderId: '577557834859',
    projectId: 'charlotte-78955',
    authDomain: 'charlotte-78955.firebaseapp.com',
    storageBucket: 'charlotte-78955.firebasestorage.app',
    measurementId: 'G-F6CSK5L95W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVUynD6hF4RHFDqTUnTuwUgoruw5vlQXA',
    appId: '1:577557834859:android:4ba46dae55ee89c090d52e',
    messagingSenderId: '577557834859',
    projectId: 'charlotte-78955',
    storageBucket: 'charlotte-78955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-b-ZRR4a9IWwbTX-gz5UUjM15lxSa4No',
    appId: '1:577557834859:ios:92b3d01005686ab090d52e',
    messagingSenderId: '577557834859',
    projectId: 'charlotte-78955',
    storageBucket: 'charlotte-78955.firebasestorage.app',
    iosBundleId: 'com.example.charlot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-b-ZRR4a9IWwbTX-gz5UUjM15lxSa4No',
    appId: '1:577557834859:ios:92b3d01005686ab090d52e',
    messagingSenderId: '577557834859',
    projectId: 'charlotte-78955',
    storageBucket: 'charlotte-78955.firebasestorage.app',
    iosBundleId: 'com.example.charlot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7qoHY3_nWT1Emk1Kdi6QnvlM19xy56m4',
    appId: '1:577557834859:web:363d3d401876bc1990d52e',
    messagingSenderId: '577557834859',
    projectId: 'charlotte-78955',
    authDomain: 'charlotte-78955.firebaseapp.com',
    storageBucket: 'charlotte-78955.firebasestorage.app',
    measurementId: 'G-6PNM7WM7Y3',
  );

}